create table if not exists public.content_os_settings (
  key text primary key,
  value text not null
);

create table if not exists public.content_os_drafts (
  id bigint generated by default as identity primary key,
  channel_key text not null check (channel_key in ('liga','gifts')),
  format_key text not null,
  text text not null,
  hook_score integer not null default 0,
  source_title text,
  source_url text,
  source_hash text,
  status text not null default 'review',
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  published_message_id bigint,
  unique(channel_key, source_hash)
);

create table if not exists public.content_os_video_jobs (
  id bigint generated by default as identity primary key,
  draft_id bigint not null references public.content_os_drafts(id) on delete cascade,
  payload text not null,
  status text not null default 'ready',
  result_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.content_os_channel_posts (
  id bigint generated by default as identity primary key,
  channel_key text not null,
  source_channel text not null,
  source_role text not null check (source_role in ('own','radar')),
  telegram_post_id bigint not null,
  text text not null,
  views bigint,
  reactions bigint not null default 0,
  forwards bigint not null default 0,
  media_kind text,
  media_ref text,
  posted_at timestamptz,
  imported_at timestamptz not null default now(),
  unique(source_channel, telegram_post_id)
);

alter table public.content_os_channel_posts add column if not exists reactions bigint not null default 0;
alter table public.content_os_channel_posts add column if not exists forwards bigint not null default 0;
alter table public.content_os_channel_posts add column if not exists media_kind text;
alter table public.content_os_channel_posts add column if not exists media_ref text;

create table if not exists public.content_os_post_metrics (
  id bigint generated by default as identity primary key,
  draft_id bigint not null references public.content_os_drafts(id) on delete cascade,
  views bigint not null default 0,
  reactions bigint not null default 0,
  forwards bigint not null default 0,
  engagement double precision not null default 0,
  captured_at timestamptz not null default now()
);

create table if not exists public.content_os_match_jobs (
  id bigint generated by default as identity primary key,
  external_id text,
  source_type text not null check (source_type in ('url','telegram')),
  source_ref text not null,
  player_ref text not null,
  analysis_mode text not null check (analysis_mode in ('player','team','full')),
  status text not null default 'queued',
  progress integer not null default 0 check (progress between 0 and 100),
  result_url text,
  error text,
  metrics_json text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.content_os_match_jobs add column if not exists metrics_json text;

create table if not exists public.content_os_players (
  id bigint generated by default as identity primary key,
  display_name text not null,
  birth_year integer,
  position text,
  strong_foot text,
  created_at timestamptz not null default now()
);

create table if not exists public.content_os_player_matches (
  player_id bigint not null references public.content_os_players(id) on delete cascade,
  match_job_id bigint not null references public.content_os_match_jobs(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(player_id,match_job_id)
);

create table if not exists public.content_os_service_orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  username text,
  offer_key text not null,
  brief text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.content_os_funnel_events (
  id bigint generated by default as identity primary key,
  user_id bigint,
  event_type text not null check (event_type in ('landing','offer_view','order_created')),
  source text,
  offer_key text,
  created_at timestamptz not null default now()
);

create table if not exists public.content_os_course_notes (
  id bigint generated by default as identity primary key,
  source_channel text not null,
  message_id bigint not null,
  text text not null,
  posted_at timestamptz,
  imported_at timestamptz not null default now(),
  unique(source_channel,message_id)
);

alter table public.content_os_settings enable row level security;
alter table public.content_os_drafts enable row level security;
alter table public.content_os_video_jobs enable row level security;
alter table public.content_os_channel_posts enable row level security;
alter table public.content_os_post_metrics enable row level security;
alter table public.content_os_match_jobs enable row level security;
alter table public.content_os_players enable row level security;
alter table public.content_os_player_matches enable row level security;
alter table public.content_os_service_orders enable row level security;
alter table public.content_os_funnel_events enable row level security;
alter table public.content_os_course_notes enable row level security;

-- Content OS uses the service_role key only on Railway. No public policies are created.
