create table if not exists public.content_os_settings (
  key text primary key,
  value text not null
);

create table if not exists public.content_os_drafts (
  id bigint generated by default as identity primary key,
  channel_key text not null check (channel_key in ('liga','gifts')),
  format_key text not null,
  text text not null,
  hook_score integer not null default 0,
  source_title text,
  source_url text,
  source_hash text,
  status text not null default 'review',
  scheduled_at timestamptz,
  created_at timestamptz not null default now(),
  published_at timestamptz,
  published_message_id bigint,
  unique(channel_key, source_hash)
);

create table if not exists public.content_os_video_jobs (
  id bigint generated by default as identity primary key,
  draft_id bigint not null references public.content_os_drafts(id) on delete cascade,
  payload text not null,
  status text not null default 'ready',
  result_url text,
  created_at timestamptz not null default now()
);

create table if not exists public.content_os_channel_posts (
  id bigint generated by default as identity primary key,
  channel_key text not null,
  source_channel text not null,
  source_role text not null check (source_role in ('own','radar')),
  telegram_post_id bigint not null,
  text text not null,
  views bigint,
  posted_at timestamptz,
  imported_at timestamptz not null default now(),
  unique(source_channel, telegram_post_id)
);

create table if not exists public.content_os_post_metrics (
  id bigint generated by default as identity primary key,
  draft_id bigint not null references public.content_os_drafts(id) on delete cascade,
  views bigint not null default 0,
  reactions bigint not null default 0,
  forwards bigint not null default 0,
  engagement double precision not null default 0,
  captured_at timestamptz not null default now()
);

alter table public.content_os_settings enable row level security;
alter table public.content_os_drafts enable row level security;
alter table public.content_os_video_jobs enable row level security;
alter table public.content_os_channel_posts enable row level security;
alter table public.content_os_post_metrics enable row level security;

-- Content OS uses the service_role key only on Railway. No public policies are created.
