const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();tg?.setHeaderColor?.('#090a0c');tg?.setBackgroundColor?.('#090a0c');
let data=null,tab='today';const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const plain=s=>String(s??'').replace(/<[^>]*>/g,'').replace(/\s+/g,' ').trim(),empty=()=>$('#empty').innerHTML;
async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(options.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.json()}
const metric=(value,label,cls='')=>`<div class="metric"><b class="${cls}">${esc(value)}</b><span>${label}</span></div>`;
function draftCard(x){const action=x.status==='review'?`<button class="primary" data-action="approve" data-id="${x.id}">Одобрить</button><button class="danger" data-action="delete" data-id="${x.id}">Убрать</button>`:x.status==='approved'?`<button class="primary" data-action="publish" data-id="${x.id}">Опубликовать</button>`:'';return `<article class="card ${x.channel_key}"><div class="meta"><span class="badge">${x.channel_key==='gifts'?'GIFTS':'LIGA'}</span><span>${esc(x.format_key)} · ${esc(x.status)}</span></div><h3>${esc(plain(x.text).slice(0,115))}</h3><p>${esc(plain(x.text).slice(115,280))}</p>${action?`<div class="actions">${action}</div>`:''}</article>`}
function head(label,title,count){$('#section-label').textContent=label;$('#section-title').textContent=title;$('#section-count').textContent=count}
function render(){document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));let html='';
 if(tab==='today'){const rows=data.drafts.filter(x=>['review','approved'].includes(x.status));head('TODAY','Очередь решений',rows.length);html=`<div class="list">${rows.map(draftCard).join('')}</div>`}
 if(tab==='projects'){head('PROJECTS','Три продукта · одна система',3);html=`<div class="list"><article class="card gifts"><span class="eyebrow">MARKET INTELLIGENCE</span><h3>Gifts Intelligence</h3><p>${data.market.length} сигналов радара · ${data.drafts.filter(x=>x.channel_key==='gifts').length} последних материалов</p></article><article class="card liga"><span class="eyebrow">PLAYER DEVELOPMENT</span><h3>LigaProgress</h3><p>${data.players.length} паспортов · ${data.challenges.length} тренировочных механик</p></article><article class="card ready"><span class="eyebrow">PRODUCTION & SALES</span><h3>AI Content Lab</h3><p>${data.experiments.length} экспериментов · ${data.orders.length} активных заявок</p></article></div>`}
 if(tab==='content'){head('CONTENT','Последние материалы',data.drafts.length);html=`<div class="list">${data.drafts.map(draftCard).join('')}</div>`}
 if(tab==='calendar'){head('CALENDAR','План публикаций',data.calendar.length);html=`<div class="list">${data.calendar.map(x=>`<article class="card ${x.channel_key}"><div class="meta"><span class="badge">${esc(x.channel_key)}</span><span>${new Date(x.scheduled_at).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}</span></div><h3>${esc(plain(x.text).slice(0,160))}</h3></article>`).join('')}</div>`}
 if(tab==='growth'){head('GROWTH','Метрики и эксперименты',data.experiments.length);const winners=data.analytics.slice(0,4).map((x,i)=>`<article class="card ready"><div class="meta"><span class="badge">WINNER ${i+1}</span><b>${Number(x.engagement||0).toFixed(1)}% ER</b></div><h3>${esc(plain(x.text).slice(0,120))}</h3><p>${x.views||0} просмотров · ${x.reactions||0} реакций · ${x.forwards||0} пересылок</p></article>`).join('');const experiments=data.experiments.map(x=>`<article class="card"><div class="meta"><span class="badge">${esc(x.project)}</span><span>${esc(x.status)}</span></div><h3>${esc(x.hypothesis)}</h3><p>Меняем только: ${esc(x.variable)}<br>Control: ${esc(x.control)} → Challenger: ${esc(x.challenger)}<br>Метрика: ${esc(x.metric)}</p>${x.uplift_percent!=null?`<div class="progress"><i style="width:${Math.max(2,Math.min(100,50+Number(x.uplift_percent)))}%"></i></div>`:''}</article>`).join('');html=`<div class="list">${winners}${experiments}</div>`}
 if(tab==='studio'){head('STUDIO','Производственный конвейер',2);html=`<div class="list"><article class="card ready"><span class="eyebrow">SHORTS V2</span><h3>Сценарий → голос → сцены → субтитры → MP4</h3><p>Рендер после подтверждения. Голос, кадры и субтитры заменяются независимо.</p></article><article class="card ready"><span class="eyebrow">VISUAL DIRECTOR</span><h3>14 новых 3D-сцен</h3><p>Только 3D production pool, смысловой подбор, anti-repeat и три свежих варианта.</p></article></div>`}
 if(tab==='football'){head('FOOTBALL LAB','Паспорта и челленджи',data.challenges.length);const players=data.players.map(x=>`<article class="card liga"><div class="meta"><span class="badge">PLAYER #${x.id}</span><span>${esc(x.birth_year||'')}</span></div><h3>${esc(x.display_name)}</h3><p>${esc(x.position||'Позиция не указана')} · ${esc(x.strong_foot||'нога не указана')}</p></article>`).join('');const challenges=data.challenges.map(x=>`<article class="card liga"><div class="meta"><span class="badge">${esc(x.position)}</span><span>${x.duration_min} мин</span></div><h3>${esc(x.title)}</h3><p>${esc(x.task)}<br><br><b>Зачёт:</b> ${esc(x.success_metric)}</p><div class="actions"><button class="primary" data-challenge="${x.key}" data-do="draft">В черновик</button><button data-challenge="${x.key}" data-do="complete">Выполнено</button></div></article>`).join('');html=`<div class="list">${players}${challenges}</div>`}
 if(tab==='market'){head('MARKET DESK','Сигналы для редактора',data.market.length);html=`<div class="list">${data.market.map(x=>`<article class="card gifts"><div class="meta"><span class="badge">RADAR</span><span>не факт-пак</span></div><h3>${esc(plain(x.text).slice(0,190))}</h3><p>Используется как тема, а не доказательство рыночного утверждения</p></article>`).join('')}</div>`}
 if(tab==='sales'){const e=data.funnel.events||{};head('SALES','Воронка и заявки',data.orders.length);html=`<div class="metrics">${metric(e.visit||e.landing||0,'Переходы')}${metric(e.lead||0,'Лиды')}${metric(e.order||e.order_created||0,'Заказы')}${metric((data.funnel.revenue||0).toLocaleString('ru-RU')+' ₽','Выручка','money')}</div><div class="list">${data.orders.map(x=>`<article class="card"><div class="meta"><span class="badge">ЗАЯВКА #${x.id}</span><span>${esc(x.status)}</span></div><h3>${esc(x.offer_key)}</h3><p>${esc(plain(x.brief).slice(0,220))}</p></article>`).join('')}</div>`}
 if(tab==='knowledge'){const count=data.knowledge.reduce((a,x)=>a+Number(x.count||0),0);head('KNOWLEDGE','Операционная память',count);html=`<div class="list">${data.knowledge.map(x=>`<article class="card"><div class="meta"><span class="badge">PLAYBOOK</span><b>${x.count} частей</b></div><h3>${esc(x.source_channel)}</h3><p>${Number(x.chars||0).toLocaleString('ru-RU')} знаков знаний без копирования</p></article>`).join('')}</div>`}
 if(tab==='system'){head('SYSTEM','Готовность подключений',data.system.length);html=`<div class="system-grid">${data.system.map(x=>`<div class="system-item ${x.ready?'ready':''}"><i></i><b>${esc(x.title)}</b><span>${x.ready?'готов':esc(x.warning||('нужно: '+(x.missing||[]).join(', ')))}</span></div>`).join('')}</div>`}
 $('#content').innerHTML=html||empty()}
async function load(){try{$('#status').textContent='Обновляю данные…';data=await api('/api/dashboard');const d=new Date(data.generated_at);$('#day').textContent=d.toLocaleDateString('ru-RU',{day:'2-digit'});$('#month').textContent=d.toLocaleDateString('ru-RU',{month:'short'}).replace('.','');$('#status').textContent=data.counts.review?`${data.counts.review} материалов ждут решения`:'Критических решений сейчас нет';$('#metrics').innerHTML=metric(data.counts.review,'На ревью')+metric(data.counts.scheduled,'В плане')+metric(data.counts.published,'Вышло')+metric(data.counts.orders,'Заявки');render()}catch(e){$('#status').textContent='Открой кабинет кнопкой из Telegram-бота';$('#content').innerHTML=`<div class="empty"><span>!</span><b>Нет защищённого доступа</b><p>${esc(e.message)}</p></div>`}}
$('#tabs').onclick=e=>{if(e.target.dataset.tab){tab=e.target.dataset.tab;render();tg?.HapticFeedback?.selectionChanged()}};$('#refresh').onclick=load;$('#content').onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.action)await api(`/api/drafts/${b.dataset.id}/${b.dataset.action}`,{method:'POST'});if(b.dataset.challenge)await api(`/api/challenges/${b.dataset.challenge}/${b.dataset.do}`,{method:'POST',body:'{}'});tg?.HapticFeedback?.notificationOccurred('success');await load()}catch(err){tg?.showAlert?.(err.message)}};load();
