const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();tg?.setHeaderColor?.('#0b0b0f');tg?.setBackgroundColor?.('#0b0b0f');
const state={items:[],filter:'all',selected:null};const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,options={}){const res=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(options.headers||{})}});if(!res.ok)throw new Error(await res.text()||'Ошибка');return res.json()}
const vertical={football:'FOOTBALL LAB',ai:'CONTENT LAB',gifts:'GIFTS INTELLIGENCE'};const tier={free:'БЕСПЛАТНО',entry:'СТАРТ',core:'ОСНОВНОЕ',system:'СИСТЕМА',recurring:'ПОДПИСКА'};
function render(){const items=state.items.filter(x=>state.filter==='all'||x.vertical===state.filter);$('#count').textContent=items.length;$('#catalog').innerHTML=items.map(x=>`<article class="service ${esc(x.vertical)}"><div class="top"><span class="pill">${esc(vertical[x.vertical])}</span><span class="pill">${esc(tier[x.tier])}</span></div><h3>${esc(x.title)}</h3><p>${esc(x.promise)}</p><div class="bottom"><div><span class="price">${esc(x.price)}</span><span class="time">${esc(x.turnaround)}</span></div><button class="open" data-key="${esc(x.key)}" aria-label="Открыть">↗</button></div></article>`).join('');document.querySelectorAll('.open').forEach(b=>b.onclick=()=>openOrder(b.dataset.key))}
function openOrder(key){state.selected=state.items.find(x=>x.key===key);if(!state.selected)return;if(state.selected.external_url){tg?.openTelegramLink?.(state.selected.external_url);return}$('#modal-tier').textContent=vertical[state.selected.vertical]+' · '+tier[state.selected.tier];$('#modal-title').textContent=state.selected.title;$('#modal-promise').textContent=state.selected.promise+' Получишь: '+state.selected.deliverables.join(', ')+'.';$('#brief').value='';$('#error').textContent='';$('#order').showModal();tg?.HapticFeedback?.impactOccurred('light')}
document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelector('#filters .active').classList.remove('active');b.classList.add('active');state.filter=b.dataset.filter;render();tg?.HapticFeedback?.selectionChanged()});
$('#diagnose').onclick=()=>openOrder('content_doctor');$('#submit').onclick=async()=>{const brief=$('#brief').value.trim();if(brief.length<12){$('#error').textContent='Опиши задачу хотя бы одним полным предложением';return}const button=$('#submit');button.disabled=true;button.textContent='Отправляю…';try{const result=await api('/api/shop/orders',{method:'POST',body:JSON.stringify({package_key:state.selected.key,brief})});tg?.HapticFeedback?.notificationOccurred('success');$('#order').close();tg?.showPopup?.({title:'Заявка принята',message:`Заявка #${result.order_id}. Мы сначала проверим задачу и вернёмся с точным следующим шагом.`,buttons:[{type:'ok'}]})}catch(e){$('#error').textContent=e.message.includes('Unauthorized')?'Открой магазин кнопкой внутри Telegram-бота':e.message;tg?.HapticFeedback?.notificationOccurred('error')}finally{button.disabled=false;button.innerHTML='Отправить заявку <span>→</span>'}};
api('/api/shop/catalog').then(data=>{state.items=data.packages;render()}).catch(e=>{$('#catalog').innerHTML=`<div class="service"><h3>Не удалось открыть каталог</h3><p>${esc(e.message)}. Открой магазин из меню Telegram-бота.</p></div>`});
