const tg=window.Telegram?.WebApp;
tg?.ready();tg?.expand();tg?.setHeaderColor?.('#090a0c');tg?.setBackgroundColor?.('#090a0c');
const state={items:[],filter:'featured',selected:null};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const featured=['content_doctor','football_episode','single_short','player_development','telegram_growth','gifts_intelligence'];
const vertical={football:'FOOTBALL LAB',ai:'CONTENT STUDIO',gifts:'GIFTS INTELLIGENCE'};
const tier={free:'ДИАГНОСТИКА',entry:'ТОЧЕЧНО',core:'ПАКЕТ',system:'СИСТЕМА',recurring:'ДОСТУП'};
const titles={featured:'То, с чего стоит начать',football:'Разбор и развитие игрока',ai:'Контент и автоматизация',gifts:'Доступ к аналитике'};
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':tg?.initData||'',...(options.headers||{})}});if(!response.ok)throw new Error(await response.text()||'Ошибка');return response.json()}
function visibleItems(){if(state.filter==='featured')return featured.map(key=>state.items.find(item=>item.key===key)).filter(Boolean);return state.items.filter(item=>item.vertical===state.filter)}
function render(){const items=visibleItems();$('#count').textContent=String(items.length).padStart(2,'0');$('#catalog-title').textContent=titles[state.filter]||'Решения';$('#catalog').innerHTML=items.map((item,index)=>`<article class="service" data-index="${String(index+1).padStart(2,'0')}"><div class="top"><span class="discipline">${esc(vertical[item.vertical])}</span><span class="tier">${esc(tier[item.tier])}</span></div><h3>${esc(item.title)}</h3><p>${esc(item.promise)}</p><div class="bottom"><div><span class="price">${esc(item.price)}</span><span class="time">${esc(item.turnaround)}</span></div><button class="open" data-key="${esc(item.key)}" aria-label="Открыть">↗</button></div></article>`).join('');document.querySelectorAll('.open').forEach(button=>button.onclick=()=>openOrder(button.dataset.key))}
function openOrder(key){state.selected=state.items.find(item=>item.key===key);if(!state.selected)return;if(state.selected.external_url){tg?.openTelegramLink?.(state.selected.external_url);return}$('#modal-tier').textContent=`${vertical[state.selected.vertical]} / ${tier[state.selected.tier]}`;$('#modal-title').textContent=state.selected.title;$('#modal-promise').textContent=state.selected.promise;$('#modal-deliverables').innerHTML=state.selected.deliverables.map(item=>`<span>${esc(item)}</span>`).join('');$('#modal-price').textContent=state.selected.price;$('#modal-time').textContent=state.selected.turnaround;$('#brief').value='';$('#error').textContent='';$('#order').showModal();tg?.HapticFeedback?.impactOccurred('light')}
document.querySelectorAll('#filters button').forEach(button=>button.onclick=()=>{document.querySelector('#filters .active')?.classList.remove('active');button.classList.add('active');state.filter=button.dataset.filter;render();tg?.HapticFeedback?.selectionChanged()});
$('#diagnose').onclick=$('#dock-diagnose').onclick=()=>openOrder('content_doctor');
$('#submit').onclick=async()=>{const brief=$('#brief').value.trim();if(brief.length<12){$('#error').textContent='Опиши задачу хотя бы одним полным предложением';return}const button=$('#submit');button.disabled=true;button.textContent='Отправляем…';try{const result=await api('/api/shop/orders',{method:'POST',body:JSON.stringify({package_key:state.selected.key,brief})});tg?.HapticFeedback?.notificationOccurred('success');$('#order').close();tg?.showPopup?.({title:'Заявка принята',message:`Номер ${result.order_id}. Проверим задачу и напишем с точным следующим шагом.`,buttons:[{type:'ok'}]})}catch(error){$('#error').textContent=error.message.includes('Unauthorized')?'Открой витрину кнопкой внутри Telegram-бота':error.message;tg?.HapticFeedback?.notificationOccurred('error')}finally{button.disabled=false;button.innerHTML='Отправить заявку <span>↗</span>'}};
api('/api/shop/catalog').then(result=>{state.items=result.packages;render()}).catch(error=>{$('#catalog').innerHTML=`<article class="service" data-index="!"><h3>Витрина не загрузилась</h3><p>${esc(error.message)}. Открой её кнопкой внутри Telegram.</p></article>`});
